services:
  - type: web
   name: link
   env: node
   buildCommand: |
       bash -c "/opt/render/project/nodes/node-22.12.0/bin/npm install --force && /opt/render/project/nodes/node-22.12.0/bin/npm rebuild sqlite3"
   startCommand: node app.js